sudo: required

language: node_js

node_js:
  - "4.2.4"

services:
  - docker
  - mongodb
  - redis

before_install:
  - npm i -g -U npm
  - docker build -t orientboard/react-orientboard .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push orientboard/react-orientboard

install:
  - npm install --registry=https://registry.npmjs.org/

before_script:
  - gulp build-test
  - npm start

script:
  - gulp test
