sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t orientboard/react-orientboard .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.example.com
  - docker push orientboard/react-orientboard
